name: mofa_mobile

description: "MOFA App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  provider: ^6.1.2
  mm_nrc: ^0.0.3
  collection: ^1.19.1
  get_it: ^8.2.0
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Pyidaungsu
      fonts:
        - asset: assets/fonts/Pyidaungsu-Regular.ttf
        - asset: assets/fonts/Pyidaungsu-Bold.ttf
          weight: 700
